### ISSUE TITLE
Error Uncaught 1589038614221 and 1589896619445 are too far apart with stepSize of 1 second

### ISSUE THREAD

**Issue by raitisbe** [DailisLangovskis/sensor-data#6]
![image](https://user-images.githubusercontent.com/395514/82336358-254b0e80-99f3-11ea-9997-5daa0d5c1318.png)
Until I click larger interval like month or day

**Comment by DailisLangovskis** [comment]
Function buttons now have different purpose. There should not be any more errors when using them.
